name: 🐍 Generate Snake

on:
  schedule:
    - cron: "0 16 * * *" # 北京时间每天 0 点
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 生成贡献蛇 SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Birditch
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 推送到 output 分支
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
